apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frigate-dev
resources:
  - ../local-dev
configMapGenerator:
  - name: frigate-dev-maintenance-restore
    files:
      - restore_state.py
patches:
  - target:
      kind: Deployment
      name: frigate-dev
    path: patch.json
