mqtt:
  enabled: false

database:
  path: /data/frigate.db

detectors:
  cpu:
    type: cpu

semantic_search:
  enabled: false
  device: CPU

record:
  enabled: false

snapshots:
  enabled: false

birdseye:
  enabled: false

cameras:
  dev_camera:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_CAMERA_HOST}
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 2
