apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frigate-dev

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: frigate-dev-config
    files:
      - config.yml
    options:
      labels:
        app.kubernetes.io/name: frigate-dev
        app.kubernetes.io/part-of: frigate
        app.kubernetes.io/environment: development
