name: On release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - id: lowercaseRepo
        uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
        with:
          string: ${{ github.repository }}
      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tag variables
        env:
          TAG: ${{ github.ref_name }}
          LOWERCASE_REPO: ${{ steps.lowercaseRepo.outputs.lowercase }}
        run: |
          set -euo pipefail
          build_type=$([[ "${TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo "stable" || echo "beta")
          clean_version="${TAG,,}"
          clean_version="${clean_version#v}"
          {
            echo "BUILD_TYPE=${build_type}"
            echo "BASE=ghcr.io/${LOWERCASE_REPO}"
            echo "BUILD_TAG=${GITHUB_SHA::7}"
            echo "CLEAN_VERSION=${clean_version}"
          } >> "${GITHUB_ENV}"
      - name: Tag and push the main image
        run: |
          set -euo pipefail
          version_tag="${BASE}:${CLEAN_VERSION}"
          stable_tag="${BASE}:stable"
          pull_tag="${BASE}:${BUILD_TAG}"
          docker run --rm -v "${HOME}/.docker/config.json:/config.json:ro" quay.io/skopeo/stable:latest copy --authfile /config.json --multi-arch all "docker://${pull_tag}" "docker://${version_tag}"
          for variant in standard-arm64 tensorrt tensorrt-jp6 rk rocm synaptics; do
            docker run --rm -v "${HOME}/.docker/config.json:/config.json:ro" quay.io/skopeo/stable:latest copy --authfile /config.json --multi-arch all "docker://${pull_tag}-${variant}" "docker://${version_tag}-${variant}"
          done

          # stable tag
          if [[ "${BUILD_TYPE}" == "stable" ]]; then
            docker run --rm -v "${HOME}/.docker/config.json:/config.json:ro" quay.io/skopeo/stable:latest copy --authfile /config.json --multi-arch all "docker://${pull_tag}" "docker://${stable_tag}"
            for variant in standard-arm64 tensorrt tensorrt-jp6 rk rocm synaptics; do
              docker run --rm -v "${HOME}/.docker/config.json:/config.json:ro" quay.io/skopeo/stable:latest copy --authfile /config.json --multi-arch all "docker://${pull_tag}-${variant}" "docker://${stable_tag}-${variant}"
            done
          fi
